// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1RWIcXaxh9yckh_bu_QSu1MxICbFL_XM',
    appId: '1:966824896811:web:469cc3096dd82aa9d1bd6e',
    messagingSenderId: '966824896811',
    projectId: 'zoom-clone-5ec5f',
    authDomain: 'zoom-clone-5ec5f.firebaseapp.com',
    storageBucket: 'zoom-clone-5ec5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuTQg6YQrZl0yAJpUhe0mvYCl8HV9t2vk',
    appId: '1:966824896811:android:57678be03a9f417dd1bd6e',
    messagingSenderId: '966824896811',
    projectId: 'zoom-clone-5ec5f',
    storageBucket: 'zoom-clone-5ec5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsIhd5srqGPMHQ4eDuvmYbJouD-hQZAO8',
    appId: '1:966824896811:ios:c30c937424c08345d1bd6e',
    messagingSenderId: '966824896811',
    projectId: 'zoom-clone-5ec5f',
    storageBucket: 'zoom-clone-5ec5f.appspot.com',
    iosClientId: '966824896811-60rq25u1dp98n8nqokv0pj57d9spjbqv.apps.googleusercontent.com',
    iosBundleId: 'com.zoom.clone.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsIhd5srqGPMHQ4eDuvmYbJouD-hQZAO8',
    appId: '1:966824896811:ios:c30c937424c08345d1bd6e',
    messagingSenderId: '966824896811',
    projectId: 'zoom-clone-5ec5f',
    storageBucket: 'zoom-clone-5ec5f.appspot.com',
    iosClientId: '966824896811-60rq25u1dp98n8nqokv0pj57d9spjbqv.apps.googleusercontent.com',
    iosBundleId: 'com.zoom.clone.zoomClone',
  );
}
